//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace DependencyInjection.Lifetime.Analyzers;

using System.Globalization;
using System.Resources;

/// <summary>
/// A strongly-typed resource class for looking up localized strings.
/// </summary>
internal static class Resources
{
    private static ResourceManager? _resourceManager;

    /// <summary>
    /// Gets the cached ResourceManager instance used by this class.
    /// </summary>
    internal static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager(
            "DependencyInjection.Lifetime.Analyzers.Resources",
            typeof(Resources).Assembly);

    /// <summary>
    /// Overrides the current thread's CurrentUICulture property for all
    /// resource lookups using this strongly typed resource class.
    /// </summary>
    internal static CultureInfo? Culture { get; set; }

    // DI001: Scope Must Be Disposed

    /// <summary>
    /// Looks up a localized string: Add 'using' statement
    /// </summary>
    internal static string DI001_FixTitle_AddUsing =>
        ResourceManager.GetString("DI001_FixTitle_AddUsing", Culture) ?? "Add 'using' statement";

    /// <summary>
    /// Looks up a localized string: Add 'await using' statement
    /// </summary>
    internal static string DI001_FixTitle_AddAwaitUsing =>
        ResourceManager.GetString("DI001_FixTitle_AddAwaitUsing", Culture) ?? "Add 'await using' statement";

    // DI002: Scope Escape

    /// <summary>
    /// Looks up a localized string: Add TODO comment
    /// </summary>
    internal static string DI002_FixTitle_AddTodo =>
        ResourceManager.GetString("DI002_FixTitle_AddTodo", Culture) ?? "Add TODO comment";

    /// <summary>
    /// Looks up a localized string: Suppress with #pragma
    /// </summary>
    internal static string DI002_FixTitle_Suppress =>
        ResourceManager.GetString("DI002_FixTitle_Suppress", Culture) ?? "Suppress with #pragma";

    // DI003: Captive Dependency

    /// <summary>
    /// Looks up a localized string: Change to Scoped lifetime
    /// </summary>
    internal static string DI003_FixTitle_ChangeToScoped =>
        ResourceManager.GetString("DI003_FixTitle_ChangeToScoped", Culture) ?? "Change to Scoped lifetime";

    /// <summary>
    /// Looks up a localized string: Change to Transient lifetime
    /// </summary>
    internal static string DI003_FixTitle_ChangeToTransient =>
        ResourceManager.GetString("DI003_FixTitle_ChangeToTransient", Culture) ?? "Change to Transient lifetime";

    /// <summary>
    /// Looks up a localized string: Change dependency to Singleton
    /// </summary>
    internal static string DI003_FixTitle_UpgradeDependency =>
        ResourceManager.GetString("DI003_FixTitle_UpgradeDependency", Culture) ?? "Change dependency to Singleton";

    // DI005: Async Scope Required

    /// <summary>
    /// Looks up a localized string: Use 'CreateAsyncScope()'
    /// </summary>
    internal static string DI005_FixTitle =>
        ResourceManager.GetString("DI005_FixTitle", Culture) ?? "Use 'CreateAsyncScope()'";

    // DI006: Static Provider Cache

    /// <summary>
    /// Looks up a localized string: Remove 'static' modifier
    /// </summary>
    internal static string DI006_FixTitle_RemoveStatic =>
        ResourceManager.GetString("DI006_FixTitle_RemoveStatic", Culture) ?? "Remove 'static' modifier";

    // DI008: Disposable Transient

    /// <summary>
    /// Looks up a localized string: Change to 'AddScoped'
    /// </summary>
    internal static string DI008_FixTitle_ChangeToScoped =>
        ResourceManager.GetString("DI008_FixTitle_ChangeToScoped", Culture) ?? "Change to 'AddScoped'";

    /// <summary>
    /// Looks up a localized string: Change to 'AddSingleton'
    /// </summary>
    internal static string DI008_FixTitle_ChangeToSingleton =>
        ResourceManager.GetString("DI008_FixTitle_ChangeToSingleton", Culture) ?? "Change to 'AddSingleton'";

    /// <summary>
    /// Looks up a localized string: Use factory registration
    /// </summary>
    internal static string DI008_FixTitle_UseFactory =>
        ResourceManager.GetString("DI008_FixTitle_UseFactory", Culture) ?? "Use factory registration";

    // DI009: Open Generic Lifetime Mismatch

    /// <summary>
    /// Looks up a localized string: Change open generic to Scoped
    /// </summary>
    internal static string DI009_FixTitle_ChangeToScoped =>
        ResourceManager.GetString("DI009_FixTitle_ChangeToScoped", Culture) ?? "Change open generic to Scoped";

    /// <summary>
    /// Looks up a localized string: Change open generic to Transient
    /// </summary>
    internal static string DI009_FixTitle_ChangeToTransient =>
        ResourceManager.GetString("DI009_FixTitle_ChangeToTransient", Culture) ?? "Change open generic to Transient";

    /// <summary>
    /// Looks up a localized string: Change dependency to Singleton
    /// </summary>
    internal static string DI009_FixTitle_UpgradeDependency =>
        ResourceManager.GetString("DI009_FixTitle_UpgradeDependency", Culture) ?? "Change dependency to Singleton";
}
