name: Feature request
description: Suggest a new analyzer rule, code fix, or project enhancement
title: "feature: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the analyzer/code-fix behavior you want.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: List alternatives or workarounds you evaluated.
  - type: textarea
    id: examples
    attributes:
      label: Example code
      description: Provide sample code showing expected diagnostics or fixes.
      render: csharp
